apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-go-rhtap-three-component-scenarios-zwba
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sruk-tenant/mc-three-scenarios/devfile-go-rhtap-three-component-scenarios-zwba@sha256:7a5148f90d23f7c271598acb42e8cc70382525ee0e267346552255732b402274
        name: my-go
        resources: {}
status: {}
