apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: node-nodevfile-nodocker-rhtap-three-component-scenarios-xnij
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sruk-tenant/mc-three-scenarios/node-nodevfile-nodocker-rhtap-three-component-scenarios-xnij@sha256:f6905a5f4263ec78c0f5590b322204e90ebc79dca57cfa11f42c526a73d6d7f2
        name: my-nodejs
        resources: {}
status: {}
